### ISSUE TITLE
거래게시판 CSS

### ISSUE THREAD

**Issue by rabbitS2** [inuit57/WebTeamProject3#148]
BBB

**Comment by inuit57** [comment]
https://github.com/inuit57/WebTeamProject3/commit/be324b3499f71a77ffc033214be2e55ac6721c04

CSS 상품페이지 목록 깨지는 문제

이걸로 복구하기?

**Comment by inuit57** [comment]
부트스트랩 쪽 문제 

.justify-content-end {
    justify-content: center;
}

.card-img, .card-img-bottom, .card-img-top {
    width: 100%;
    height: 180px;
}
