### ISSUE TITLE
[기능 개발] 상품 게시판 

### ISSUE THREAD

**Issue by inuit57** [inuit57/WebTeamProject3#18]
# 필수 구현
- [x] CRUD 기능
- [x] 이미지 등록 (최대 3개)
- [ ] 거래지역 설정
- [x] 상품 가격 등록 ( 무료 나눔 체크 버튼) 
- [x] 조회수 중복 막기 ( 쿠키 활용 - { IP , 글번호 } ) 

## 추가 구현
- [x] 찜 횟수 표시 
- [x] 거래여부 표시 
- [x] 신고하기
- [ ] 위치기능
- [ ] ~몇시간전

**Comment by hongju913** [comment]
신고하기
