### ISSUE TITLE
[기능 개발] 경매 시스템

### ISSUE THREAD

**Issue by inuit57** [inuit57/WebTeamProject3#23]
## 개요 
- 사용자는 상품 등록시 "경매 등록 요청"을 할 수 있다. (경매 시작가 설정 가능)
- 관리자는 경매 요청이 들어온 건에 대해서 경매 채팅을 관리 주관하도록 한다. 
- 이 기능이 잘 구현될 경우, 경매 사이트로 방향을 바꾸는 것도 고려해볼 것. 

## 필수 구현
- 1:N 채팅방 구현 
- 현재 최대 금액 표시 
- 사용자는 현재 보유한 포인트 안에서 경매 참여 가능
- 사용자는 "숫자"만을 채팅에 입력 가능 

## 추가 구현
- 사용자는 현재 최대 금액보다 3배 이상인 금액은 입력 불가 (갑자기 금액이 뛰는 일을 막기 위함)
- [100] [1000] [10000] 과 같은 버튼 형식으로 입력을 지원. (버튼을 누를 경우, 현재 최대 금액 + 버튼 금액 자동 등록)
- 입력에 일정 딜레이를 주어서 동일한 가격 입력이 들어오는 것을 막도록 하기.

**Comment by inuit57** [comment]
[자료참고1](https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=scw0531&logNo=221097188275)

**Comment by inuit57** [comment]
[자료참고2](https://hwiveloper.dev/2019/01/10/spring-boot-stomp-websocket/)
- 이게 좀 더 좋아보인다

**Comment by minggu33** [comment]
와우 참고자료까지! 😋

**Comment by inuit57** [comment]
채팅방 DB 생각 중인 구조 

<채팅방>
- 방번호
- 방인원 수 
- 방장 이름?

<채팅방 목록>
- 방번호
- 참가자 이름(FK) - 사용자 ID 

<채팅방 메시지>
- 방번호
- 글쓴이
- 메시지 내용
- 보낸 시각 (날짜 + 시간 + 분)

**Comment by inuit57** [comment]
[참고자료3](https://m.blog.naver.com/scw0531/221097188275)

**Comment by inuit57** [comment]
[참고자료4](https://klyhyeon.tistory.com/157)
- 우리와 유사하게 판매자-구매자 채팅 구현으로 보여진다.

**Comment by inuit57** [comment]
[참고자료5](https://myhappyman.tistory.com/100?category=873296)
이거 보면서 다시 작업 진행 중....

**Comment by inuit57** [comment]
http://localhost/chat

이상하게도 저거 예제대로 하니까 port 번호 안 적어도 된다. 
그리고 망할 spring 부트 왜 jsp 지원 안 해주는 거냐고 ...

**Comment by inuit57** [comment]
-보류-
