### ISSUE TITLE
[기능 개선] 회원 정보 수정 

### ISSUE THREAD

**Issue by inuit57** [inuit57/WebTeamProject3#48]
# 추가 구현

- [x]  프로필 사진 오른쪽이나 위에 이미지 형태로 볼 수 있도록 하기
- [x]  주소 수정 가능하도록 하기 
- [x]  통장 정보 입력할 수 있도록 하기

**Comment by rabbitS2** [comment]
회원정보 수정 유효성 필요

**Comment by rabbitS2** [comment]
비밀번호 수정 null값 막기

**Comment by rabbitS2** [comment]
비밀번호 수정 유효성(회원가입할때랑 동일한걸로)

**Comment by rabbitS2** [comment]
닉네임수정....

**Comment by inuit57** [comment]
> 닉네임수정....

닉네임을 PK로 이걸 수정 못하니까 
ID를 PK로 주도록 하자. 

아니면 닉네임을 수정하지 못하게 한다??
