### ISSUE TITLE
[의논 필요] 회원 테이블 구조 

### ISSUE THREAD

**Issue by inuit57** [inuit57/WebTeamProject3#49]
- 회원 번호가 필요한 지에 대한 논의 필요. 

- 닉네임 또는 아이디 값을 PK로 놓는다면 굳이 사용하지 않아도 된다. 
- AI ( auto increment ) 설정으로 인해서 장기적으로 보았을 때 문제가 발생할 수 있다.

**Comment by rabbitS2** [comment]
상세 주소를 일반주소랑 합치는 쪽으로 하고싶습니다

**Comment by inuit57** [comment]
1) 회원 번호 삭제 -> user_nickname을 PK로. 
2) 탈퇴 여부 처리하는 부분 - (0,1)에서 (1,2)로 변경
3) 관리자 여부 처리하는 부분 - (0,1)에서 (1,2)로 변경
