### ISSUE TITLE
[그냥 의견] 회원프로필

### ISSUE THREAD

**Issue by hongju913** [inuit57/WebTeamProject3#67]
상품 글 올린 글쓴이 정보 누르면 
글쓴이가 쓴 글 정보 불러오기

**Comment by inuit57** [comment]
상품페이지에서 작성자 이름에 링크 걸어놓고 누르면 그 사람이 쓴 글 조회하도록 작업할게요~

**Comment by inuit57** [comment]
우선은 상품 페이지에서 글쓴 사람 이름 누르면 검색 되게끔 구현
